# Form implementation generated from reading ui file 'C:\BridgeCalc\ui\janela_memorial_esforco_resultante.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_janela_memorial_esforco_resultante(object):
    def setupUi(self, janela_memorial_esforco_resultante):
        janela_memorial_esforco_resultante.setObjectName("janela_memorial_esforco_resultante")
        janela_memorial_esforco_resultante.resize(1030, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(janela_memorial_esforco_resultante.sizePolicy().hasHeightForWidth())
        janela_memorial_esforco_resultante.setSizePolicy(sizePolicy)
        janela_memorial_esforco_resultante.setMinimumSize(QtCore.QSize(1030, 650))
        janela_memorial_esforco_resultante.setMaximumSize(QtCore.QSize(1030, 650))
        self.verticalLayout = QtWidgets.QVBoxLayout(janela_memorial_esforco_resultante)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=janela_memorial_esforco_resultante)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(1000000, 100000))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -13, 997, 1591))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.confirmar = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.confirmar.setGeometry(QtCore.QRect(900, 1560, 81, 26))
        self.confirmar.setAutoDefault(False)
        self.confirmar.setObjectName("confirmar")
        self.manual = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.manual.setGeometry(QtCore.QRect(870, 1560, 25, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.manual.setFont(font)
        self.manual.setAutoDefault(False)
        self.manual.setObjectName("manual")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 0, 281, 271))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(10, 20, 261, 251))
        self.label.setWordWrap(True)
        self.label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(290, 0, 691, 271))
        self.groupBox.setObjectName("groupBox")
        self.tabela_resumo = QtWidgets.QTableWidget(parent=self.groupBox)
        self.tabela_resumo.setGeometry(QtCore.QRect(10, 20, 671, 245))
        self.tabela_resumo.setObjectName("tabela_resumo")
        self.tabela_resumo.setColumnCount(0)
        self.tabela_resumo.setRowCount(4)
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 280, 211, 51))
        self.groupBox_5.setObjectName("groupBox_5")
        self.exportar_tabela = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.exportar_tabela.setGeometry(QtCore.QRect(10, 20, 91, 26))
        self.exportar_tabela.setAutoDefault(False)
        self.exportar_tabela.setObjectName("exportar_tabela")
        self.exportar = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.exportar.setGeometry(QtCore.QRect(110, 20, 91, 26))
        self.exportar.setAutoDefault(False)
        self.exportar.setObjectName("exportar")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_2.setGeometry(QtCore.QRect(370, 280, 611, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 241, 26))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.combo_longarina = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.combo_longarina.setGeometry(QtCore.QRect(250, 20, 161, 26))
        self.combo_longarina.setObjectName("combo_longarina")
        self.combo_exibir_anotacao = QtWidgets.QCheckBox(parent=self.groupBox_2)
        self.combo_exibir_anotacao.setGeometry(QtCore.QRect(430, 20, 171, 26))
        self.combo_exibir_anotacao.setObjectName("combo_exibir_anotacao")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 340, 981, 600))
        self.groupBox_4.setObjectName("groupBox_4")
        self.desenho_1 = QtWidgets.QFrame(parent=self.groupBox_4)
        self.desenho_1.setGeometry(QtCore.QRect(10, 20, 961, 571))
        self.desenho_1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.desenho_1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.desenho_1.setObjectName("desenho_1")
        self.groupBox_6 = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 950, 981, 600))
        self.groupBox_6.setObjectName("groupBox_6")
        self.desenho_2 = QtWidgets.QFrame(parent=self.groupBox_6)
        self.desenho_2.setGeometry(QtCore.QRect(10, 20, 961, 571))
        self.desenho_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.desenho_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.desenho_2.setObjectName("desenho_2")
        self.memorial_completo = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.memorial_completo.setGeometry(QtCore.QRect(220, 300, 131, 26))
        self.memorial_completo.setAutoDefault(False)
        self.memorial_completo.setObjectName("memorial_completo")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(janela_memorial_esforco_resultante)
        QtCore.QMetaObject.connectSlotsByName(janela_memorial_esforco_resultante)

    def retranslateUi(self, janela_memorial_esforco_resultante):
        _translate = QtCore.QCoreApplication.translate
        janela_memorial_esforco_resultante.setWindowTitle(_translate("janela_memorial_esforco_resultante", "Memorial Cálculo do Esforço Resultante"))
        self.confirmar.setText(_translate("janela_memorial_esforco_resultante", "OK"))
        self.manual.setToolTip(_translate("janela_memorial_esforco_resultante", "Dúvidas? Acesse o manual referente a essa janela"))
        self.manual.setText(_translate("janela_memorial_esforco_resultante", "?"))
        self.groupBox_3.setTitle(_translate("janela_memorial_esforco_resultante", "Relação Fundamental"))
        self.label.setText(_translate("janela_memorial_esforco_resultante", "<div style=\"font-family: \'Times New Roman\', serif; font-size: 13pt; line-height: 1.6;\">\n"
"    <div style=\"font-size: 18pt; margin-bottom: 15px; display: flex; align-items: middle;\">\n"
"        <i>E</i> = <i>q</i> · <span style=\"font-size: 26pt; vertical-align: -15%;\">∫</span> <i>y</i>(<i>x</i>)<i>dx</i>\n"
"    </div>\n"
"\n"
"    <div style=\"border-top: 1px solid #444; width: 100px; margin-bottom: 10px;\"></div>\n"
"\n"
"    <div style=\"font-size: 11pt;\">\n"
"        <b style=\"font-size: 12pt;\">onde:</b>\n"
"        <ul style=\"list-style-type: none; margin-left: -25px; margin-top: 5px;\">\n"
"            <li style=\"margin-bottom: 8px;\">\n"
"                • <b><i>E</i></b>: é o esforço resultante (kNm ou kN, conforme o tipo de solicitação analisada);\n"
"            </li>\n"
"            <li style=\"margin-bottom: 8px;\">\n"
"                • <b><i>q</i></b>: é a intensidade da carga distribuída (kN/m);\n"
"            </li>\n"
"            <li>\n"
"                • <b><i>y</i>(<i>x</i>)</b>: é o valor da ordenada da linha de influência no ponto de aplicação <i>x</i>.\n"
"            </li>\n"
"        </ul>\n"
"    </div>\n"
"</div>"))
        self.groupBox.setTitle(_translate("janela_memorial_esforco_resultante", "Resumo Cálculo dos Esforços"))
        self.groupBox_5.setTitle(_translate("janela_memorial_esforco_resultante", "Exportar"))
        self.exportar_tabela.setText(_translate("janela_memorial_esforco_resultante", "Tabela"))
        self.exportar.setText(_translate("janela_memorial_esforco_resultante", "Desenho"))
        self.groupBox_2.setTitle(_translate("janela_memorial_esforco_resultante", "Desenho"))
        self.label_2.setText(_translate("janela_memorial_esforco_resultante", "Selecione a Longarina que deseja visualizar:"))
        self.combo_exibir_anotacao.setText(_translate("janela_memorial_esforco_resultante", "Exibir Detalhes de Cálculo"))
        self.groupBox_4.setTitle(_translate("janela_memorial_esforco_resultante", "Seção AA"))
        self.groupBox_6.setTitle(_translate("janela_memorial_esforco_resultante", "Seção BB"))
        self.memorial_completo.setText(_translate("janela_memorial_esforco_resultante", "Memorial Completo"))
