# Form implementation generated from reading ui file 'C:\BridgeCalc\ui\janela_carga_movel.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_janela_carga_movel(object):
    def setupUi(self, janela_carga_movel):
        janela_carga_movel.setObjectName("janela_carga_movel")
        janela_carga_movel.resize(1030, 670)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(janela_carga_movel.sizePolicy().hasHeightForWidth())
        janela_carga_movel.setSizePolicy(sizePolicy)
        janela_carga_movel.setMinimumSize(QtCore.QSize(1030, 670))
        janela_carga_movel.setMaximumSize(QtCore.QSize(1030, 670))
        self.verticalLayout = QtWidgets.QVBoxLayout(janela_carga_movel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=janela_carga_movel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(1000000, 100000))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -1551, 997, 2300))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.confirmar = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.confirmar.setGeometry(QtCore.QRect(910, 2270, 81, 26))
        self.confirmar.setAutoDefault(False)
        self.confirmar.setObjectName("confirmar")
        self.cancelar = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.cancelar.setGeometry(QtCore.QRect(820, 2270, 81, 26))
        self.cancelar.setAutoDefault(False)
        self.cancelar.setObjectName("cancelar")
        self.manual = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.manual.setGeometry(QtCore.QRect(790, 2270, 25, 26))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.manual.setFont(font)
        self.manual.setAutoDefault(False)
        self.manual.setObjectName("manual")
        self.calcular = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.calcular.setGeometry(QtCore.QRect(360, 1655, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.calcular.setFont(font)
        self.calcular.setAutoDefault(False)
        self.calcular.setObjectName("calcular")
        self.groupBox_7 = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 380, 971, 631))
        self.groupBox_7.setObjectName("groupBox_7")
        self.desenho = QtWidgets.QFrame(parent=self.groupBox_7)
        self.desenho.setGeometry(QtCore.QRect(10, 44, 951, 571))
        self.desenho.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.desenho.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.desenho.setObjectName("desenho")
        self.atualizar_qframe_desenho = QtWidgets.QPushButton(parent=self.groupBox_7)
        self.atualizar_qframe_desenho.setGeometry(QtCore.QRect(410, 15, 151, 26))
        self.atualizar_qframe_desenho.setAutoDefault(False)
        self.atualizar_qframe_desenho.setObjectName("atualizar_qframe_desenho")
        self.groupBox_tremo_tipo = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_tremo_tipo.setGeometry(QtCore.QRect(10, 1030, 971, 601))
        self.groupBox_tremo_tipo.setObjectName("groupBox_tremo_tipo")
        self.desenho_2 = QtWidgets.QFrame(parent=self.groupBox_tremo_tipo)
        self.desenho_2.setGeometry(QtCore.QRect(10, 270, 951, 321))
        self.desenho_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.desenho_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.desenho_2.setObjectName("desenho_2")
        self.trem_critico = QtWidgets.QRadioButton(parent=self.groupBox_tremo_tipo)
        self.trem_critico.setGeometry(QtCore.QRect(60, 20, 141, 24))
        self.trem_critico.setObjectName("trem_critico")
        self.trem_longarina = QtWidgets.QRadioButton(parent=self.groupBox_tremo_tipo)
        self.trem_longarina.setGeometry(QtCore.QRect(240, 20, 211, 24))
        self.trem_longarina.setObjectName("trem_longarina")
        self.combo_longarina = QtWidgets.QComboBox(parent=self.groupBox_tremo_tipo)
        self.combo_longarina.setGeometry(QtCore.QRect(250, 70, 181, 26))
        self.combo_longarina.setObjectName("combo_longarina")
        self.line = QtWidgets.QFrame(parent=self.groupBox_tremo_tipo)
        self.line.setGeometry(QtCore.QRect(180, 20, 61, 121))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.line_3 = QtWidgets.QFrame(parent=self.groupBox_tremo_tipo)
        self.line_3.setGeometry(QtCore.QRect(430, 20, 61, 121))
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.html_trem_tipo = QtWidgets.QLabel(parent=self.groupBox_tremo_tipo)
        self.html_trem_tipo.setGeometry(QtCore.QRect(30, 150, 921, 91))
        self.html_trem_tipo.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.html_trem_tipo.setObjectName("html_trem_tipo")
        self.trem_carga = QtWidgets.QRadioButton(parent=self.groupBox_tremo_tipo)
        self.trem_carga.setGeometry(QtCore.QRect(620, 20, 211, 24))
        self.trem_carga.setObjectName("trem_carga")
        self.html_q = QtWidgets.QLabel(parent=self.groupBox_tremo_tipo)
        self.html_q.setGeometry(QtCore.QRect(530, 50, 181, 23))
        self.html_q.setObjectName("html_q")
        self.spin_q = QtWidgets.QDoubleSpinBox(parent=self.groupBox_tremo_tipo)
        self.spin_q.setGeometry(QtCore.QRect(740, 50, 141, 23))
        self.spin_q.setObjectName("spin_q")
        self.spin_q1 = QtWidgets.QDoubleSpinBox(parent=self.groupBox_tremo_tipo)
        self.spin_q1.setGeometry(QtCore.QRect(740, 80, 141, 23))
        self.spin_q1.setObjectName("spin_q1")
        self.html_q1 = QtWidgets.QLabel(parent=self.groupBox_tremo_tipo)
        self.html_q1.setGeometry(QtCore.QRect(530, 80, 181, 23))
        self.html_q1.setObjectName("html_q1")
        self.spin_q2 = QtWidgets.QDoubleSpinBox(parent=self.groupBox_tremo_tipo)
        self.spin_q2.setGeometry(QtCore.QRect(740, 110, 141, 23))
        self.spin_q2.setObjectName("spin_q2")
        self.html_q2 = QtWidgets.QLabel(parent=self.groupBox_tremo_tipo)
        self.html_q2.setGeometry(QtCore.QRect(530, 110, 181, 23))
        self.html_q2.setObjectName("html_q2")
        self.atualizar_q_frame_desenho_2 = QtWidgets.QPushButton(parent=self.groupBox_tremo_tipo)
        self.atualizar_q_frame_desenho_2.setGeometry(QtCore.QRect(410, 240, 151, 26))
        self.atualizar_q_frame_desenho_2.setAutoDefault(False)
        self.atualizar_q_frame_desenho_2.setObjectName("atualizar_q_frame_desenho_2")
        self.groupBox_coef = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_coef.setGeometry(QtCore.QRect(10, 0, 971, 361))
        self.groupBox_coef.setObjectName("groupBox_coef")
        self.line_2 = QtWidgets.QFrame(parent=self.groupBox_coef)
        self.line_2.setGeometry(QtCore.QRect(460, 20, 61, 331))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.coef_automatico = QtWidgets.QRadioButton(parent=self.groupBox_coef)
        self.coef_automatico.setGeometry(QtCore.QRect(10, 30, 141, 24))
        self.coef_automatico.setObjectName("coef_automatico")
        self.coef_manual = QtWidgets.QRadioButton(parent=self.groupBox_coef)
        self.coef_manual.setGeometry(QtCore.QRect(510, 30, 231, 24))
        self.coef_manual.setObjectName("coef_manual")
        self.table_coef = QtWidgets.QTableWidget(parent=self.groupBox_coef)
        self.table_coef.setGeometry(QtCore.QRect(20, 70, 461, 261))
        self.table_coef.setObjectName("table_coef")
        self.table_coef.setColumnCount(0)
        self.table_coef.setRowCount(0)
        self.table_coef_manual = QtWidgets.QTableWidget(parent=self.groupBox_coef)
        self.table_coef_manual.setGeometry(QtCore.QRect(500, 70, 461, 261))
        self.table_coef_manual.setObjectName("table_coef_manual")
        self.table_coef_manual.setColumnCount(0)
        self.table_coef_manual.setRowCount(0)
        self.groupBox_8 = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 1700, 621, 581))
        self.groupBox_8.setObjectName("groupBox_8")
        self.html_resultados_esforcos = QtWidgets.QTextEdit(parent=self.groupBox_8)
        self.html_resultados_esforcos.setGeometry(QtCore.QRect(10, 20, 601, 551))
        self.html_resultados_esforcos.setReadOnly(True)
        self.html_resultados_esforcos.setObjectName("html_resultados_esforcos")
        self.groupBox_6 = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_6.setGeometry(QtCore.QRect(650, 1700, 321, 181))
        self.groupBox_6.setObjectName("groupBox_6")
        self.botao_cortante = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.botao_cortante.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        self.botao_cortante.setFont(font)
        self.botao_cortante.setAutoDefault(False)
        self.botao_cortante.setObjectName("botao_cortante")
        self.botao_momento = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.botao_momento.setGeometry(QtCore.QRect(10, 80, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        self.botao_momento.setFont(font)
        self.botao_momento.setAutoDefault(False)
        self.botao_momento.setObjectName("botao_momento")
        self.botao_reacoes = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.botao_reacoes.setGeometry(QtCore.QRect(10, 130, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        self.botao_reacoes.setFont(font)
        self.botao_reacoes.setAutoDefault(False)
        self.botao_reacoes.setObjectName("botao_reacoes")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(janela_carga_movel)
        QtCore.QMetaObject.connectSlotsByName(janela_carga_movel)

    def retranslateUi(self, janela_carga_movel):
        _translate = QtCore.QCoreApplication.translate
        janela_carga_movel.setWindowTitle(_translate("janela_carga_movel", "Análise da Carga Móvel"))
        self.confirmar.setText(_translate("janela_carga_movel", "Confirmar"))
        self.cancelar.setText(_translate("janela_carga_movel", "Cancelar"))
        self.manual.setToolTip(_translate("janela_carga_movel", "Dúvidas? Acesse o manual referente a essa janela"))
        self.manual.setText(_translate("janela_carga_movel", "?"))
        self.calcular.setText(_translate("janela_carga_movel", "CALCULAR ENVOLTÓRIAS"))
        self.groupBox_7.setTitle(_translate("janela_carga_movel", "Distribuição do Coeficiente de Impacto sobre a Estrutura"))
        self.atualizar_qframe_desenho.setText(_translate("janela_carga_movel", "Atualizar Visualização"))
        self.groupBox_tremo_tipo.setTitle(_translate("janela_carga_movel", "Trem Tipo Longitudinal da Longaria"))
        self.trem_critico.setText(_translate("janela_carga_movel", "Caso Crítico"))
        self.trem_longarina.setText(_translate("janela_carga_movel", "Selecionar Longarina (Manual)"))
        self.html_trem_tipo.setText(_translate("janela_carga_movel", "<html>\n"
"    <body style=\'font-family: \"Segoe UI\", Tahoma, sans-serif; margin: 0; padding: 8px; background-color: #2b2b2b; color: white;\'>\n"
"\n"
"        <div style=\'text-align: center; font-size: 11pt; font-weight: bold; color: #ffffff; margin-bottom: 10px; border-bottom: 1px solid #555; padding-bottom: 4px;\'>\n"
"            Parâmetros Trem-Tipo Longitudinal (Longarina)\n"
"        </div>\n"
"\n"
"        <div style=\'margin-bottom: 8px; padding: 6px; background: rgba(52, 152, 219, 0.1); border-radius: 4px; border-left: 3px solid #3498db;\'>\n"
"            <span style=\'font-size: 9pt; color: #3498db; font-weight: bold; text-transform: uppercase;\'>Carregamento:</span>\n"
"            <span style=\'font-size: 10pt; margin-left: 10px; color: #eee;\'>\n"
"                Carga Concentrada (<b>Q</b>): <b>45 kN</b>  |\n"
"                Carga Distribuída Externa (<b>q<sub>1</sub></b>): <b>5 kN/m</b>  |\n"
"                Carga Distribuída Interna (<b>q<sub>2</sub></b>): <b>12 kN/m</b>\n"
"            </span>\n"
"        </div>\n"
"\n"
"        <div style=\'padding: 6px; background: rgba(241, 196, 15, 0.05); border-radius: 4px; border-left: 3px solid #f1c40f;\'>\n"
"            <span style=\'font-size: 9pt; color: #f1c40f; font-weight: bold; text-transform: uppercase;\'>Geometria:</span>\n"
"            <span style=\'font-size: 10pt; margin-left: 10px; color: #ddd;\'>\n"
"                Espaçamento entre Eixos: <b>150 cm</b>  |\n"
"                Extensão do Veículo: <b>6.00 m</b>  |\n"
"                Largura de Influência: <b>3.00 m</b>\n"
"            </span>\n"
"        </div>\n"
"\n"
"    </body>\n"
"    </html>"))
        self.trem_carga.setText(_translate("janela_carga_movel", "Definir Cargas (Manual)"))
        self.html_q.setText(_translate("janela_carga_movel", "<html>\n"
"        <body style=\'font-family: \"Segoe UI\", Tahoma, sans-serif; margin: 0; padding: 0; background-color: transparent;\'>\n"
"            <div style=\'padding: 6px; background: rgba(149, 165, 166, 0.05); border-radius: 4px; border-left: 3px solid #7f8c8d; display: inline-block;\'>\n"
"                <span style=\'font-size: 10pt; color: #888;\'>Carga Concentrada (<b>Q</b>):</span>\n"
"            </div>\n"
"        </body>\n"
"        </html>"))
        self.html_q1.setText(_translate("janela_carga_movel", "<html>\n"
"        <body style=\'font-family: \"Segoe UI\", Tahoma, sans-serif; margin: 0; padding: 0; background-color: transparent;\'>\n"
"            <div style=\'padding: 6px; background: rgba(52, 152, 219, 0.1); border-radius: 4px; border-left: 3px solid #3498db; display: inline-block;\'>\n"
"                <span style=\'font-size: 10pt; color: #eee;\'>Carga Distribuída Externa (<b>q<sub>1</sub></b>):</span>\n"
"            </div>\n"
"        </body>\n"
"        </html>"))
        self.html_q2.setText(_translate("janela_carga_movel", "<html>\n"
"        <body style=\'font-family: \"Segoe UI\", Tahoma, sans-serif; margin: 0; padding: 0; background-color: transparent;\'>\n"
"            <div style=\'padding: 6px; background: rgba(52, 152, 219, 0.1); border-radius: 4px; border-left: 3px solid #3498db; display: inline-block;\'>\n"
"                <span style=\'font-size: 10pt; color: #eee;\'>Carga Distribuída Interna (<b>q<sub>2</sub></b>):</span>\n"
"            </div>\n"
"        </body>\n"
"        </html>"))
        self.atualizar_q_frame_desenho_2.setText(_translate("janela_carga_movel", "Atualizar Visualização"))
        self.groupBox_coef.setTitle(_translate("janela_carga_movel", "Coeficiente de Impacto (φ)"))
        self.coef_automatico.setText(_translate("janela_carga_movel", "Cálculo Automático"))
        self.coef_manual.setText(_translate("janela_carga_movel", "Valor Personalizado (Manual)"))
        self.groupBox_8.setTitle(_translate("janela_carga_movel", "Resumo das Seções Críticas"))
        self.html_resultados_esforcos.setHtml(_translate("janela_carga_movel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\" bgcolor=\"#1e1e1e\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:14px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:14pt; font-weight:700; color:#90caf9; background-color:#252525;\">φ·Cortante </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; font-weight:700; color:#e0e0e0;\">Máximo em S10 (45.00 m):</span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> </span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; color:#e0e0e0;\"><br /></span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">φ·V</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">min</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e57373;\">-30.00 kN</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">  |  φ·V</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">max</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#81c784;\">+850.00 kN</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; font-weight:700; color:#e0e0e0;\">Mínimo em S5 (22.50 m):</span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> </span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; color:#e0e0e0;\"><br /></span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">φ·V</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">min</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e57373;\">-180.00 kN</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">  |  φ·V</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">max</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#81c784;\">+400.00 kN</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'sans-serif\'; font-size:11.5pt; font-weight:700; color:#ffffff;\">Convenção:</span><span style=\" font-family:\'sans-serif\'; font-size:10pt; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:6px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'sans-serif\'; font-size:10pt; font-weight:700; color:#81c784;\">(+) Cortante Positivo:</span><span style=\" font-family:\'sans-serif\'; font-size:10pt; color:#e0e0e0;\"> Rotação horária → </span><span style=\" font-family:\'sans-serif\'; font-size:10pt; font-weight:700; color:#e0e0e0;\">Tração diagonal (/) → Estribos</span><span style=\" font-family:\'sans-serif\'; font-size:10pt; color:#e0e0e0;\"> <br /></span><span style=\" font-family:\'sans-serif\'; font-size:10pt; font-weight:700; color:#e57373;\">(-) Cortante Negativo:</span><span style=\" font-family:\'sans-serif\'; font-size:10pt; color:#e0e0e0;\"> Rotação anti-horária → </span><span style=\" font-family:\'sans-serif\'; font-size:10pt; font-weight:700; color:#e0e0e0;\">Tração diagonal (\\) → Estribos</span><span style=\" font-family:\'sans-serif\'; font-size:10pt; color:#e0e0e0;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; color:#e0e0e0;\"><br /></span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:14px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:14pt; font-weight:700; color:#90caf9; background-color:#252525;\">φ·Momento </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; font-weight:700; color:#e0e0e0;\">Máximo em S7 (31.50 m):</span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> </span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; color:#e0e0e0;\"><br /></span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">φ·M</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">min</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e57373;\">-950.00 kN·m</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">  |  φ·M</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">max</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#81c784;\">+2800.00 kN·m</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; font-weight:700; color:#e0e0e0;\">Mínimo em S2 (9.00 m):</span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> </span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; color:#e0e0e0;\"><br /></span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">φ·M</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">min</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e57373;\">-2100.00 kN·m</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">  |  φ·M</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">max</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#81c784;\">+600.00 kN·m</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'sans-serif\'; font-size:13pt; font-weight:700; color:#ffffff;\">Convenção:</span><span style=\" font-family:\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:8px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'sans-serif\'; font-size:11pt; font-weight:700; color:#81c784;\">(+) Positivo:</span><span style=\" font-family:\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> Tração embaixo → </span><span style=\" font-family:\'sans-serif\'; font-size:11pt; font-weight:700; color:#e0e0e0;\">Armadura Inferior</span><span style=\" font-family:\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> <br /></span><span style=\" font-family:\'sans-serif\'; font-size:11pt; font-weight:700; color:#e57373;\">(-) Negativo:</span><span style=\" font-family:\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> Tração em cima → </span><span style=\" font-family:\'sans-serif\'; font-size:11pt; font-weight:700; color:#e0e0e0;\">Armadura Superior</span><span style=\" font-family:\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; color:#e0e0e0;\"><br /></span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:14px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:14pt; font-weight:700; color:#90caf9; background-color:#252525;\">φ·Reações </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; font-weight:700; color:#e0e0e0;\">Máximo em Apoio A (0.00 m):</span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> </span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; color:#e0e0e0;\"><br /></span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">φ·R</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">min</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e57373;\">-120.00 kN</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">  |  φ·R</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">max</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#81c784;\">+280.00 kN</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; font-weight:700; color:#e0e0e0;\">Mínimo em Apoio B (60.00 m):</span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> </span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; color:#e0e0e0;\"><br /></span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">φ·R</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">min</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e57373;\">-160.00 kN</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">  |  φ·R</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">max</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#81c784;\">+40.00 kN</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'sans-serif\'; font-size:11.5pt; font-weight:700; color:#ffffff;\">Convenção:</span><span style=\" font-family:\'sans-serif\'; font-size:10pt; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:6px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'sans-serif\'; font-size:10pt; font-weight:700; color:#81c784;\">(+) Para cima:</span><span style=\" font-family:\'sans-serif\'; font-size:10pt; color:#e0e0e0;\"> Reação vertical ascendente. <br /></span><span style=\" font-family:\'sans-serif\'; font-size:10pt; font-weight:700; color:#e57373;\">(-) Para baixo:</span><span style=\" font-family:\'sans-serif\'; font-size:10pt; color:#e0e0e0;\"> Reação vertical descendente. </span></p></body></html>"))
        self.groupBox_6.setTitle(_translate("janela_carga_movel", "Visualizar Detalhes"))
        self.botao_cortante.setText(_translate("janela_carga_movel", "Cortante"))
        self.botao_momento.setText(_translate("janela_carga_movel", "Momento Fletor"))
        self.botao_reacoes.setText(_translate("janela_carga_movel", "Reação de Apoio"))
