# Form implementation generated from reading ui file 'C:\BridgeCalc\ui\janela_peso_proprio.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_janela_peso_proprio(object):
    def setupUi(self, janela_peso_proprio):
        janela_peso_proprio.setObjectName("janela_peso_proprio")
        janela_peso_proprio.resize(1030, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(janela_peso_proprio.sizePolicy().hasHeightForWidth())
        janela_peso_proprio.setSizePolicy(sizePolicy)
        janela_peso_proprio.setMinimumSize(QtCore.QSize(1030, 650))
        janela_peso_proprio.setMaximumSize(QtCore.QSize(1030, 650))
        self.verticalLayout = QtWidgets.QVBoxLayout(janela_peso_proprio)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=janela_peso_proprio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(1000000, 100000))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 997, 1950))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 0, 981, 671))
        self.groupBox_3.setObjectName("groupBox_3")
        self.desenho = QtWidgets.QFrame(parent=self.groupBox_3)
        self.desenho.setGeometry(QtCore.QRect(10, 20, 961, 321))
        self.desenho.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.desenho.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.desenho.setObjectName("desenho")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.groupBox_3)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 360, 961, 171))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.html_carga_g1 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.html_carga_g1.setGeometry(QtCore.QRect(10, 130, 931, 23))
        self.html_carga_g1.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.html_carga_g1.setObjectName("html_carga_g1")
        self.spin_gama_c = QtWidgets.QDoubleSpinBox(parent=self.groupBox_2)
        self.spin_gama_c.setGeometry(QtCore.QRect(190, 40, 121, 23))
        self.spin_gama_c.setObjectName("spin_gama_c")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 211, 23))
        self.label_2.setObjectName("label_2")
        self.html_calculo_area = QtWidgets.QLabel(parent=self.groupBox_2)
        self.html_calculo_area.setGeometry(QtCore.QRect(10, 60, 931, 71))
        self.html_calculo_area.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.html_calculo_area.setObjectName("html_calculo_area")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.groupBox_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 961, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radio_automatico = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget)
        self.radio_automatico.setObjectName("radio_automatico")
        self.horizontalLayout.addWidget(self.radio_automatico, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.groupBox_3)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 550, 961, 91))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.html_carga_g1_2 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.html_carga_g1_2.setGeometry(QtCore.QRect(10, 50, 41, 23))
        self.html_carga_g1_2.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.html_carga_g1_2.setObjectName("html_carga_g1_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.groupBox_5)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 961, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radio_manual = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget_2)
        self.radio_manual.setObjectName("radio_manual")
        self.horizontalLayout_2.addWidget(self.radio_manual, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.doubleSpinBox_g1 = QtWidgets.QDoubleSpinBox(parent=self.groupBox_5)
        self.doubleSpinBox_g1.setGeometry(QtCore.QRect(50, 50, 141, 23))
        self.doubleSpinBox_g1.setObjectName("doubleSpinBox_g1")
        self.confirmar = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.confirmar.setGeometry(QtCore.QRect(910, 1910, 81, 26))
        self.confirmar.setAutoDefault(False)
        self.confirmar.setObjectName("confirmar")
        self.cancelar = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.cancelar.setGeometry(QtCore.QRect(820, 1910, 81, 26))
        self.cancelar.setAutoDefault(False)
        self.cancelar.setObjectName("cancelar")
        self.manual = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.manual.setGeometry(QtCore.QRect(790, 1910, 25, 26))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.manual.setFont(font)
        self.manual.setAutoDefault(False)
        self.manual.setObjectName("manual")
        self.groupBox = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(10, 690, 981, 111))
        self.groupBox.setObjectName("groupBox")
        self.check_transversina = QtWidgets.QCheckBox(parent=self.groupBox)
        self.check_transversina.setGeometry(QtCore.QRect(120, 20, 171, 24))
        self.check_transversina.setObjectName("check_transversina")
        self.radio_apoio = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radio_apoio.setGeometry(QtCore.QRect(10, 50, 211, 24))
        self.radio_apoio.setObjectName("radio_apoio")
        self.radio_apoioevao = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radio_apoioevao.setGeometry(QtCore.QRect(230, 50, 211, 24))
        self.radio_apoioevao.setObjectName("radio_apoioevao")
        self.label_transversina = QtWidgets.QLabel(parent=self.groupBox)
        self.label_transversina.setGeometry(QtCore.QRect(120, 80, 61, 23))
        self.label_transversina.setObjectName("label_transversina")
        self.spin_p_transversina = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.spin_p_transversina.setGeometry(QtCore.QRect(180, 80, 121, 23))
        self.spin_p_transversina.setObjectName("spin_p_transversina")
        self.line = QtWidgets.QFrame(parent=self.groupBox)
        self.line.setGeometry(QtCore.QRect(380, 20, 21, 81))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.check_elementos_extremidade = QtWidgets.QCheckBox(parent=self.groupBox)
        self.check_elementos_extremidade.setGeometry(QtCore.QRect(400, 20, 351, 24))
        self.check_elementos_extremidade.setObjectName("check_elementos_extremidade")
        self.label_p_elementos_extremidade = QtWidgets.QLabel(parent=self.groupBox)
        self.label_p_elementos_extremidade.setGeometry(QtCore.QRect(440, 80, 61, 23))
        self.label_p_elementos_extremidade.setObjectName("label_p_elementos_extremidade")
        self.spin_p_extremidade = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.spin_p_extremidade.setGeometry(QtCore.QRect(500, 80, 121, 23))
        self.spin_p_extremidade.setObjectName("spin_p_extremidade")
        self.label_elemetos_extremidade = QtWidgets.QLabel(parent=self.groupBox)
        self.label_elemetos_extremidade.setGeometry(QtCore.QRect(460, 50, 121, 16))
        self.label_elemetos_extremidade.setObjectName("label_elemetos_extremidade")
        self.line_2 = QtWidgets.QFrame(parent=self.groupBox)
        self.line_2.setGeometry(QtCore.QRect(640, 20, 21, 81))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_laje = QtWidgets.QLabel(parent=self.groupBox)
        self.label_laje.setGeometry(QtCore.QRect(770, 20, 91, 16))
        self.label_laje.setObjectName("label_laje")
        self.label_g_placa = QtWidgets.QLabel(parent=self.groupBox)
        self.label_g_placa.setGeometry(QtCore.QRect(740, 80, 31, 23))
        self.label_g_placa.setObjectName("label_g_placa")
        self.spin_g_placa = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.spin_g_placa.setGeometry(QtCore.QRect(780, 80, 121, 23))
        self.spin_g_placa.setObjectName("spin_g_placa")
        self.label_laje2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_laje2.setGeometry(QtCore.QRect(660, 37, 311, 41))
        self.label_laje2.setWordWrap(True)
        self.label_laje2.setObjectName("label_laje2")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 810, 981, 481))
        self.groupBox_4.setObjectName("groupBox_4")
        self.desenho_2 = QtWidgets.QFrame(parent=self.groupBox_4)
        self.desenho_2.setGeometry(QtCore.QRect(10, 50, 961, 411))
        self.desenho_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.desenho_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.desenho_2.setObjectName("desenho_2")
        self.atualizar = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.atualizar.setGeometry(QtCore.QRect(420, 20, 151, 26))
        self.atualizar.setAutoDefault(False)
        self.atualizar.setObjectName("atualizar")
        self.calcular = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.calcular.setGeometry(QtCore.QRect(370, 1310, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.calcular.setFont(font)
        self.calcular.setAutoDefault(False)
        self.calcular.setObjectName("calcular")
        self.groupBox_6 = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_6.setGeometry(QtCore.QRect(650, 1350, 321, 181))
        self.groupBox_6.setObjectName("groupBox_6")
        self.botao_cortante = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.botao_cortante.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        self.botao_cortante.setFont(font)
        self.botao_cortante.setAutoDefault(False)
        self.botao_cortante.setObjectName("botao_cortante")
        self.botao_momento = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.botao_momento.setGeometry(QtCore.QRect(10, 80, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        self.botao_momento.setFont(font)
        self.botao_momento.setAutoDefault(False)
        self.botao_momento.setObjectName("botao_momento")
        self.botao_reacoes = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.botao_reacoes.setGeometry(QtCore.QRect(10, 130, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        self.botao_reacoes.setFont(font)
        self.botao_reacoes.setAutoDefault(False)
        self.botao_reacoes.setObjectName("botao_reacoes")
        self.groupBox_7 = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 1350, 621, 581))
        self.groupBox_7.setObjectName("groupBox_7")
        self.html_resultados_esforcos = QtWidgets.QTextEdit(parent=self.groupBox_7)
        self.html_resultados_esforcos.setGeometry(QtCore.QRect(10, 20, 601, 551))
        self.html_resultados_esforcos.setReadOnly(True)
        self.html_resultados_esforcos.setObjectName("html_resultados_esforcos")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(janela_peso_proprio)
        QtCore.QMetaObject.connectSlotsByName(janela_peso_proprio)

    def retranslateUi(self, janela_peso_proprio):
        _translate = QtCore.QCoreApplication.translate
        janela_peso_proprio.setWindowTitle(_translate("janela_peso_proprio", "Análise das Cargas de Peso Próprio (g1)"))
        self.groupBox_3.setTitle(_translate("janela_peso_proprio", "Definição da Ação Permanente Peso Próprio (g1)"))
        self.html_carga_g1.setText(_translate("janela_peso_proprio", "   <html>\n"
"    <body style=\'font-family: \"Times New Roman\", serif; font-size: 13pt; color: white;\'>\n"
"        <div style=\'white-space: nowrap;\'>\n"
"            <b>g<sub>1</sub></b> = A<sub>total</sub> &times; &gamma;<sub>c</sub>\n"
"            = 1.2500 &times; 25\n"
"            = <span style=\'color: #2ecc71;\'><b>31.25 kN/m</b></span>\n"
"        </div>\n"
"    </body>\n"
"    </html>"))
        self.label_2.setText(_translate("janela_peso_proprio", "<html><head/><body><p>Peso Específico do Concreto (<span style=\" font-family:\'Arial\',\'sans-serif\'; font-size:14px; font-weight:700; color:#bfbfbf; background-color:#1f1f1f;\">γ</span><span style=\" font-family:\'Arial\',\'sans-serif\'; font-size:14px; font-weight:700; color:#bfbfbf; background-color:#1f1f1f; vertical-align:sub;\">c</span><span style=\" font-family:\'Arial\',\'sans-serif\'; font-size:14px; color:#bfbfbf; background-color:#1f1f1f;\">):</span></p></body></html>"))
        self.html_calculo_area.setText(_translate("janela_peso_proprio", " <html>\n"
"    <body style=\'font-family: \"Times New Roman\", serif; font-size: 13pt; color: white;\'>\n"
"        <div style=\'white-space: nowrap;\'>\n"
"            <b>A<sub>laje</sub></b> = h<sub>laje</sub> &times; L<sub>laje</sub>\n"
"            = 10 &times; 50\n"
"            = <b>500.00 cm²</b>\n"
"\n"
"            <span style=\'margin: 0 10px; color: #7f8c8d;\'> | </span>\n"
"\n"
"            <b>A<sub>longarinas</sub></b> = A<sub>longarina</sub> &times; n&ordm;<sub>longarinas</sub>\n"
"            = 12.5 &times; 4\n"
"            = <b>50.00 cm²</b>\n"
"\n"
"            <span style=\'margin: 0 10px; color: #7f8c8d;\'> | </span>\n"
"\n"
"            <b>A<sub>total</sub></b> = A<sub>laje</sub> + A<sub>longarinas</sub>\n"
"            = <span style=\'color: #2ecc71;\'><b>550.00 cm²</b></span>\n"
"        </div>\n"
"    </body>\n"
"    </html>"))
        self.radio_automatico.setText(_translate("janela_peso_proprio", "Automático"))
        self.html_carga_g1_2.setText(_translate("janela_peso_proprio", "<html><head/><body><pre style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:13pt; font-weight:700; color:#ffffff;\">g</span><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:13pt; font-weight:700; color:#ffffff; vertical-align:sub;\">1</span><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:13pt; color:#ffffff;\"> = </span></pre></body></html>"))
        self.radio_manual.setText(_translate("janela_peso_proprio", "Manual"))
        self.confirmar.setText(_translate("janela_peso_proprio", "Confirmar"))
        self.cancelar.setText(_translate("janela_peso_proprio", "Cancelar"))
        self.manual.setToolTip(_translate("janela_peso_proprio", "Dúvidas? Acesse o manual referente a essa janela"))
        self.manual.setText(_translate("janela_peso_proprio", "?"))
        self.groupBox.setTitle(_translate("janela_peso_proprio", "Elementos Adicionais (Opcionais)"))
        self.check_transversina.setText(_translate("janela_peso_proprio", "Considerar Transversinas"))
        self.radio_apoio.setText(_translate("janela_peso_proprio", "Apenas nos apoios"))
        self.radio_apoioevao.setText(_translate("janela_peso_proprio", "Apoios e Meio do Vão"))
        self.label_transversina.setText(_translate("janela_peso_proprio", "<html><head/><body><p>P<span style=\" vertical-align:sub;\">transversina</span>:</p></body></html>"))
        self.check_elementos_extremidade.setText(_translate("janela_peso_proprio", "Considerar Elementos de Extremidade "))
        self.label_p_elementos_extremidade.setText(_translate("janela_peso_proprio", "<html><head/><body><p>P<span style=\" vertical-align:sub;\">extremidade</span>:</p></body></html>"))
        self.label_elemetos_extremidade.setText(_translate("janela_peso_proprio", "(Cortina/Console/Aba)"))
        self.label_laje.setText(_translate("janela_peso_proprio", "Laje de Transição"))
        self.label_g_placa.setText(_translate("janela_peso_proprio", "<html><head/><body><p>g<span style=\" vertical-align:sub;\">placa</span>:</p></body></html>"))
        self.label_laje2.setText(_translate("janela_peso_proprio", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700;\">Nota</span>: Disponível apenas para estruturas com laje de transição inclusa.</p></body></html>"))
        self.groupBox_4.setTitle(_translate("janela_peso_proprio", "Diagrama de Corpo Livre"))
        self.atualizar.setText(_translate("janela_peso_proprio", "Atualizar Visualização"))
        self.calcular.setText(_translate("janela_peso_proprio", "CALCULAR ESFORÇOS"))
        self.groupBox_6.setTitle(_translate("janela_peso_proprio", "Visualizar Detalhes"))
        self.botao_cortante.setText(_translate("janela_peso_proprio", "Cortante"))
        self.botao_momento.setText(_translate("janela_peso_proprio", "Momento Fletor"))
        self.botao_reacoes.setText(_translate("janela_peso_proprio", "Reação de Apoio"))
        self.groupBox_7.setTitle(_translate("janela_peso_proprio", "Resumo das Seções Críticas"))
        self.html_resultados_esforcos.setHtml(_translate("janela_peso_proprio", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\" bgcolor=\"#1e1e1e\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:14px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:14pt; font-weight:700; color:#90caf9; background-color:#252525;\">Cortante </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; font-weight:700; color:#e0e0e0;\">Máximo em S10 (45.00 m):</span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> </span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; color:#e0e0e0;\"><br /></span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">V</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">max</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#81c784;\">+300.00 kN</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; font-weight:700; color:#e0e0e0;\">Mínimo em S5 (22.50 m):</span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> </span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; color:#e0e0e0;\"><br /></span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">V</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">min</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e57373;\">-150.00 kN</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'sans-serif\'; font-size:11.5pt; font-weight:700; color:#ffffff;\">Convenção:</span><span style=\" font-family:\'sans-serif\'; font-size:10pt; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:6px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'sans-serif\'; font-size:10pt; font-weight:700; color:#81c784;\">(+) Cortante Positivo:</span><span style=\" font-family:\'sans-serif\'; font-size:10pt; color:#e0e0e0;\"> Rotação horária → </span><span style=\" font-family:\'sans-serif\'; font-size:10pt; font-weight:700; color:#e0e0e0;\">Tração diagonal (/) → Estribos</span><span style=\" font-family:\'sans-serif\'; font-size:10pt; color:#e0e0e0;\"> <br /></span><span style=\" font-family:\'sans-serif\'; font-size:10pt; font-weight:700; color:#e57373;\">(-) Cortante Negativo:</span><span style=\" font-family:\'sans-serif\'; font-size:10pt; color:#e0e0e0;\"> Rotação anti-horária → </span><span style=\" font-family:\'sans-serif\'; font-size:10pt; font-weight:700; color:#e0e0e0;\">Tração diagonal (\\) → Estribos</span><span style=\" font-family:\'sans-serif\'; font-size:10pt; color:#e0e0e0;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; color:#e0e0e0;\"><br /></span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:14px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:14pt; font-weight:700; color:#90caf9; background-color:#252525;\">Momento </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; font-weight:700; color:#e0e0e0;\">Máximo em S7 (31.50 m):</span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> </span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; color:#e0e0e0;\"><br /></span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">M</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">max</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#81c784;\">+1200.00 kN·m</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; font-weight:700; color:#e0e0e0;\">Mínimo em S2 (9.00 m):</span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> </span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; color:#e0e0e0;\"><br /></span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">M</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">min</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e57373;\">-800.00 kN·m</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'sans-serif\'; font-size:13pt; font-weight:700; color:#ffffff;\">Convenção:</span><span style=\" font-family:\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:8px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'sans-serif\'; font-size:11pt; font-weight:700; color:#81c784;\">(+) Positivo:</span><span style=\" font-family:\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> Tração embaixo → </span><span style=\" font-family:\'sans-serif\'; font-size:11pt; font-weight:700; color:#e0e0e0;\">Armadura Inferior</span><span style=\" font-family:\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> <br /></span><span style=\" font-family:\'sans-serif\'; font-size:11pt; font-weight:700; color:#e57373;\">(-) Negativo:</span><span style=\" font-family:\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> Tração em cima → </span><span style=\" font-family:\'sans-serif\'; font-size:11pt; font-weight:700; color:#e0e0e0;\">Armadura Superior</span><span style=\" font-family:\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; color:#e0e0e0;\"><br /></span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:14px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:14pt; font-weight:700; color:#90caf9; background-color:#252525;\">Reações </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; font-weight:700; color:#e0e0e0;\">Máximo em Apoio A (0.00 m):</span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> </span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; color:#e0e0e0;\"><br /></span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">R</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">max</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#81c784;\">+500.00 kN</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; font-weight:700; color:#e0e0e0;\">Mínimo em Apoio B (60.00 m):</span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> </span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; color:#e0e0e0;\"><br /></span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">R</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">min</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#81c784;\">+200.00 kN</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'sans-serif\'; font-size:11.5pt; font-weight:700; color:#ffffff;\">Convenção:</span><span style=\" font-family:\'sans-serif\'; font-size:10pt; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:6px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'sans-serif\'; font-size:10pt; font-weight:700; color:#81c784;\">(+) Para cima:</span><span style=\" font-family:\'sans-serif\'; font-size:10pt; color:#e0e0e0;\"> Reação vertical ascendente. <br /></span><span style=\" font-family:\'sans-serif\'; font-size:10pt; font-weight:700; color:#e57373;\">(-) Para baixo:</span><span style=\" font-family:\'sans-serif\'; font-size:10pt; color:#e0e0e0;\"> Reação vertical descendente. </span></p></body></html>"))
