# Form implementation generated from reading ui file 'C:\BridgeCalc\ui\janela_inicial.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_janela_inicial(object):
    def setupUi(self, janela_inicial):
        janela_inicial.setObjectName("janela_inicial")
        janela_inicial.resize(470, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(janela_inicial.sizePolicy().hasHeightForWidth())
        janela_inicial.setSizePolicy(sizePolicy)
        janela_inicial.setMinimumSize(QtCore.QSize(470, 550))
        janela_inicial.setMaximumSize(QtCore.QSize(470, 550))
        self.texto = QtWidgets.QPlainTextEdit(parent=janela_inicial)
        self.texto.setGeometry(QtCore.QRect(10, 141, 441, 361))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.texto.setFont(font)
        self.texto.setReadOnly(True)
        self.texto.setObjectName("texto")
        self.avancar = QtWidgets.QPushButton(parent=janela_inicial)
        self.avancar.setGeometry(QtCore.QRect(370, 520, 81, 26))
        self.avancar.setAutoDefault(False)
        self.avancar.setObjectName("avancar")
        self.logo = QtWidgets.QFrame(parent=janela_inicial)
        self.logo.setGeometry(QtCore.QRect(10, 20, 441, 101))
        self.logo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.logo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.logo.setObjectName("logo")

        self.retranslateUi(janela_inicial)
        QtCore.QMetaObject.connectSlotsByName(janela_inicial)

    def retranslateUi(self, janela_inicial):
        _translate = QtCore.QCoreApplication.translate
        janela_inicial.setWindowTitle(_translate("janela_inicial", "Boas-Vindas"))
        self.texto.setPlainText(_translate("janela_inicial", "Este software foi desenvolvido como Trabalho de Conclusão de Curso do curso de Engenharia Civil da Escola de Engenharia de São Carlos da Universidade de São Paulo (EESC-USP).\n"
"\n"
"Seu objetivo é auxiliar engenheiros civis e estudantes no pré-dimensionamento de longarinas de pontes, permitindo a definição do sistema estrutural, geometria e carregamentos de forma ágil e integrada.\n"
"\n"
"O programa realiza automaticamente o cálculo dos coeficientes de impacto de trem-tipo, esforços devido ao peso próprio (g1), sobrecarga (g2), carga móvel e efeitos de temperatura (em sistemas hiperestáticos), por meio de um modelo baseado em elementos finitos. Ao final, são geradas as combinações de ELU e ELS, bem como o dimensionamento das armaduras longitudinais e transversais, incluindo verificação à fadiga.\n"
"\n"
"As ferramentas e modelos de cálculo adotados foram validados com base em referências técnicas e critérios consagrados na prática da engenharia estrutural, permitindo análises rápidas, iterativas e confiáveis."))
        self.avancar.setText(_translate("janela_inicial", "Avançar"))
