# Form implementation generated from reading ui file 'C:\BridgeCalc\ui\janela_envoltoria_reacoes.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_janela_envoltoria_reacoes(object):
    def setupUi(self, janela_envoltoria_reacoes):
        janela_envoltoria_reacoes.setObjectName("janela_envoltoria_reacoes")
        janela_envoltoria_reacoes.resize(600, 607)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(janela_envoltoria_reacoes.sizePolicy().hasHeightForWidth())
        janela_envoltoria_reacoes.setSizePolicy(sizePolicy)
        janela_envoltoria_reacoes.setMinimumSize(QtCore.QSize(600, 607))
        janela_envoltoria_reacoes.setMaximumSize(QtCore.QSize(600, 607))
        self.groupbox_tabela = QtWidgets.QGroupBox(parent=janela_envoltoria_reacoes)
        self.groupbox_tabela.setGeometry(QtCore.QRect(10, 10, 581, 561))
        self.groupbox_tabela.setObjectName("groupbox_tabela")
        self.tabela_reacoes = QtWidgets.QTableWidget(parent=self.groupbox_tabela)
        self.tabela_reacoes.setGeometry(QtCore.QRect(10, 20, 561, 531))
        self.tabela_reacoes.setObjectName("tabela_reacoes")
        self.tabela_reacoes.setColumnCount(0)
        self.tabela_reacoes.setRowCount(0)
        self.manual = QtWidgets.QPushButton(parent=janela_envoltoria_reacoes)
        self.manual.setGeometry(QtCore.QRect(480, 580, 25, 26))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.manual.setFont(font)
        self.manual.setAutoDefault(False)
        self.manual.setObjectName("manual")
        self.exportar_tabela = QtWidgets.QPushButton(parent=janela_envoltoria_reacoes)
        self.exportar_tabela.setGeometry(QtCore.QRect(10, 580, 81, 26))
        self.exportar_tabela.setAutoDefault(False)
        self.exportar_tabela.setObjectName("exportar_tabela")
        self.btn_ok = QtWidgets.QPushButton(parent=janela_envoltoria_reacoes)
        self.btn_ok.setGeometry(QtCore.QRect(510, 580, 81, 26))
        self.btn_ok.setAutoDefault(False)
        self.btn_ok.setObjectName("btn_ok")

        self.retranslateUi(janela_envoltoria_reacoes)
        QtCore.QMetaObject.connectSlotsByName(janela_envoltoria_reacoes)

    def retranslateUi(self, janela_envoltoria_reacoes):
        _translate = QtCore.QCoreApplication.translate
        janela_envoltoria_reacoes.setWindowTitle(_translate("janela_envoltoria_reacoes", "Dialog"))
        self.groupbox_tabela.setTitle(_translate("janela_envoltoria_reacoes", "Tabela Reações de Apoio"))
        self.manual.setToolTip(_translate("janela_envoltoria_reacoes", "Dúvidas? Acesse o manual referente a essa janela"))
        self.manual.setText(_translate("janela_envoltoria_reacoes", "?"))
        self.exportar_tabela.setText(_translate("janela_envoltoria_reacoes", "Exportar"))
        self.btn_ok.setText(_translate("janela_envoltoria_reacoes", "Ok"))
