# Form implementation generated from reading ui file 'C:\BridgeCalc\ui\janela_memorial.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_janela_memorial(object):
    def setupUi(self, janela_memorial):
        janela_memorial.setObjectName("janela_memorial")
        janela_memorial.resize(1000, 670)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(janela_memorial.sizePolicy().hasHeightForWidth())
        janela_memorial.setSizePolicy(sizePolicy)
        janela_memorial.setMinimumSize(QtCore.QSize(1000, 670))
        janela_memorial.setMaximumSize(QtCore.QSize(1000, 670))
        self.textEdit_memorial = QtWidgets.QTextEdit(parent=janela_memorial)
        self.textEdit_memorial.setGeometry(QtCore.QRect(10, 10, 981, 621))
        self.textEdit_memorial.setReadOnly(True)
        self.textEdit_memorial.setObjectName("textEdit_memorial")
        self.exportar = QtWidgets.QPushButton(parent=janela_memorial)
        self.exportar.setGeometry(QtCore.QRect(820, 640, 81, 26))
        self.exportar.setAutoDefault(False)
        self.exportar.setObjectName("exportar")
        self.ok = QtWidgets.QPushButton(parent=janela_memorial)
        self.ok.setGeometry(QtCore.QRect(910, 640, 81, 26))
        self.ok.setAutoDefault(False)
        self.ok.setObjectName("ok")
        self.manual = QtWidgets.QPushButton(parent=janela_memorial)
        self.manual.setGeometry(QtCore.QRect(790, 640, 25, 26))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.manual.setFont(font)
        self.manual.setAutoDefault(False)
        self.manual.setObjectName("manual")

        self.retranslateUi(janela_memorial)
        QtCore.QMetaObject.connectSlotsByName(janela_memorial)

    def retranslateUi(self, janela_memorial):
        _translate = QtCore.QCoreApplication.translate
        janela_memorial.setWindowTitle(_translate("janela_memorial", "Dialog"))
        self.exportar.setText(_translate("janela_memorial", "Exportar"))
        self.ok.setText(_translate("janela_memorial", "OK"))
        self.manual.setToolTip(_translate("janela_memorial", "Dúvidas? Acesse o manual referente a essa janela"))
        self.manual.setText(_translate("janela_memorial", "?"))
