# Form implementation generated from reading ui file 'C:\BridgeCalc\ui\janela_esforcos_calculo.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_janela_esforcos_calculo(object):
    def setupUi(self, janela_esforcos_calculo):
        janela_esforcos_calculo.setObjectName("janela_esforcos_calculo")
        janela_esforcos_calculo.resize(1030, 670)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(janela_esforcos_calculo.sizePolicy().hasHeightForWidth())
        janela_esforcos_calculo.setSizePolicy(sizePolicy)
        janela_esforcos_calculo.setMinimumSize(QtCore.QSize(1030, 670))
        janela_esforcos_calculo.setMaximumSize(QtCore.QSize(1030, 670))
        self.verticalLayout = QtWidgets.QVBoxLayout(janela_esforcos_calculo)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=janela_esforcos_calculo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(1000000, 100000))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -931, 997, 1650))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.confirmar = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.confirmar.setGeometry(QtCore.QRect(910, 1620, 81, 26))
        self.confirmar.setAutoDefault(False)
        self.confirmar.setObjectName("confirmar")
        self.cancelar = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.cancelar.setGeometry(QtCore.QRect(820, 1620, 81, 26))
        self.cancelar.setAutoDefault(False)
        self.cancelar.setObjectName("cancelar")
        self.manual = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.manual.setGeometry(QtCore.QRect(790, 1620, 25, 26))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.manual.setFont(font)
        self.manual.setAutoDefault(False)
        self.manual.setObjectName("manual")
        self.calcular = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.calcular.setGeometry(QtCore.QRect(360, 930, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.calcular.setFont(font)
        self.calcular.setAutoDefault(False)
        self.calcular.setObjectName("calcular")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 1060, 621, 581))
        self.groupBox_2.setObjectName("groupBox_2")
        self.html_resultados_esforcos_calculos = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.html_resultados_esforcos_calculos.setGeometry(QtCore.QRect(10, 20, 601, 551))
        self.html_resultados_esforcos_calculos.setReadOnly(True)
        self.html_resultados_esforcos_calculos.setObjectName("html_resultados_esforcos_calculos")
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_5.setGeometry(QtCore.QRect(660, 1060, 321, 181))
        self.groupBox_5.setObjectName("groupBox_5")
        self.botao_cortante = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.botao_cortante.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        self.botao_cortante.setFont(font)
        self.botao_cortante.setAutoDefault(False)
        self.botao_cortante.setObjectName("botao_cortante")
        self.botao_momento = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.botao_momento.setGeometry(QtCore.QRect(10, 80, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        self.botao_momento.setFont(font)
        self.botao_momento.setAutoDefault(False)
        self.botao_momento.setObjectName("botao_momento")
        self.botao_reacoes = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.botao_reacoes.setGeometry(QtCore.QRect(10, 130, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        self.botao_reacoes.setFont(font)
        self.botao_reacoes.setAutoDefault(False)
        self.botao_reacoes.setObjectName("botao_reacoes")
        self.groupBox_coef = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_coef.setGeometry(QtCore.QRect(10, 0, 971, 441))
        self.groupBox_coef.setObjectName("groupBox_coef")
        self.label = QtWidgets.QLabel(parent=self.groupBox_coef)
        self.label.setGeometry(QtCore.QRect(160, 20, 651, 411))
        self.label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label.setObjectName("label")
        self.box_coef = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.box_coef.setGeometry(QtCore.QRect(10, 460, 971, 441))
        self.box_coef.setObjectName("box_coef")
        self.radio_automatico = QtWidgets.QRadioButton(parent=self.box_coef)
        self.radio_automatico.setGeometry(QtCore.QRect(150, 30, 101, 24))
        self.radio_automatico.setObjectName("radio_automatico")
        self.radio_personalizado = QtWidgets.QRadioButton(parent=self.box_coef)
        self.radio_personalizado.setGeometry(QtCore.QRect(680, 30, 111, 24))
        self.radio_personalizado.setObjectName("radio_personalizado")
        self.html_normativo = QtWidgets.QLabel(parent=self.box_coef)
        self.html_normativo.setGeometry(QtCore.QRect(50, 60, 391, 371))
        self.html_normativo.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.html_normativo.setObjectName("html_normativo")
        self.html_personalizado = QtWidgets.QLabel(parent=self.box_coef)
        self.html_personalizado.setGeometry(QtCore.QRect(550, 45, 391, 371))
        self.html_personalizado.setObjectName("html_personalizado")
        self.spin_gama_g = QtWidgets.QDoubleSpinBox(parent=self.box_coef)
        self.spin_gama_g.setGeometry(QtCore.QRect(790, 115, 84, 23))
        self.spin_gama_g.setObjectName("spin_gama_g")
        self.spin_gama_q = QtWidgets.QDoubleSpinBox(parent=self.box_coef)
        self.spin_gama_q.setGeometry(QtCore.QRect(790, 151, 84, 23))
        self.spin_gama_q.setObjectName("spin_gama_q")
        self.spin_gama_temp_q = QtWidgets.QDoubleSpinBox(parent=self.box_coef)
        self.spin_gama_temp_q.setGeometry(QtCore.QRect(790, 186, 84, 23))
        self.spin_gama_temp_q.setObjectName("spin_gama_temp_q")
        self.spin_psi0 = QtWidgets.QDoubleSpinBox(parent=self.box_coef)
        self.spin_psi0.setGeometry(QtCore.QRect(790, 292, 84, 23))
        self.spin_psi0.setObjectName("spin_psi0")
        self.spin_psi1 = QtWidgets.QDoubleSpinBox(parent=self.box_coef)
        self.spin_psi1.setGeometry(QtCore.QRect(790, 325, 84, 23))
        self.spin_psi1.setObjectName("spin_psi1")
        self.spin_psi2 = QtWidgets.QDoubleSpinBox(parent=self.box_coef)
        self.spin_psi2.setGeometry(QtCore.QRect(790, 360, 84, 23))
        self.spin_psi2.setObjectName("spin_psi2")
        self.line_5 = QtWidgets.QFrame(parent=self.box_coef)
        self.line_5.setGeometry(QtCore.QRect(470, 30, 16, 401))
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.groupBox = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(150, 980, 701, 61))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 701, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radio_elu = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget)
        self.radio_elu.setObjectName("radio_elu")
        self.horizontalLayout.addWidget(self.radio_elu, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.radio_els = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget)
        self.radio_els.setObjectName("radio_els")
        self.horizontalLayout.addWidget(self.radio_els, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(janela_esforcos_calculo)
        QtCore.QMetaObject.connectSlotsByName(janela_esforcos_calculo)

    def retranslateUi(self, janela_esforcos_calculo):
        _translate = QtCore.QCoreApplication.translate
        janela_esforcos_calculo.setWindowTitle(_translate("janela_esforcos_calculo", "Análise da Carga Móvel"))
        self.confirmar.setText(_translate("janela_esforcos_calculo", "Confirmar"))
        self.cancelar.setText(_translate("janela_esforcos_calculo", "Cancelar"))
        self.manual.setToolTip(_translate("janela_esforcos_calculo", "Dúvidas? Acesse o manual referente a essa janela"))
        self.manual.setText(_translate("janela_esforcos_calculo", "?"))
        self.calcular.setText(_translate("janela_esforcos_calculo", "CALCULAR ENVOLTÓRIAS"))
        self.groupBox_2.setTitle(_translate("janela_esforcos_calculo", "Resumo das Seções Críticas"))
        self.html_resultados_esforcos_calculos.setHtml(_translate("janela_esforcos_calculo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\" bgcolor=\"#1e1e1e\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:14px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:14pt; font-weight:700; color:#90caf9; background-color:#252525;\">Cortante </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; font-weight:700; color:#e0e0e0;\">Máximo em S10 (45.00 m):</span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> </span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; color:#e0e0e0;\"><br /></span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">V</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">min</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e57373;\">-50.30 kN</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">  |  V</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">max</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#81c784;\">+1029.30 kN</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; font-weight:700; color:#e0e0e0;\">Mínimo em S5 (22.50 m):</span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> </span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; color:#e0e0e0;\"><br /></span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">V</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">min</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e57373;\">-200.00 kN</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">  |  V</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">max</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#81c784;\">+573.20 kN</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'sans-serif\'; font-size:11.5pt; font-weight:700; color:#ffffff;\">Convenção:</span><span style=\" font-family:\'sans-serif\'; font-size:10pt; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:6px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'sans-serif\'; font-size:10pt; font-weight:700; color:#81c784;\">(+) Cortante Positivo:</span><span style=\" font-family:\'sans-serif\'; font-size:10pt; color:#e0e0e0;\"> Rotação horária → </span><span style=\" font-family:\'sans-serif\'; font-size:10pt; font-weight:700; color:#e0e0e0;\">Tração diagonal (/) → Estribos</span><span style=\" font-family:\'sans-serif\'; font-size:10pt; color:#e0e0e0;\"> <br /></span><span style=\" font-family:\'sans-serif\'; font-size:10pt; font-weight:700; color:#e57373;\">(-) Cortante Negativo:</span><span style=\" font-family:\'sans-serif\'; font-size:10pt; color:#e0e0e0;\"> Rotação anti-horária → </span><span style=\" font-family:\'sans-serif\'; font-size:10pt; font-weight:700; color:#e0e0e0;\">Tração diagonal (\\) → Estribos</span><span style=\" font-family:\'sans-serif\'; font-size:10pt; color:#e0e0e0;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; color:#e0e0e0;\"><br /></span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:14px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:14pt; font-weight:700; color:#90caf9; background-color:#252525;\">Momento </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; font-weight:700; color:#e0e0e0;\">Máximo em S7 (31.50 m):</span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> </span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; color:#e0e0e0;\"><br /></span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">M</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">min</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e57373;\">-1200.00 kN·m</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">  |  M</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">max</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#81c784;\">+3500.80 kN·m</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; font-weight:700; color:#e0e0e0;\">Mínimo em S2 (9.00 m):</span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> </span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; color:#e0e0e0;\"><br /></span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">M</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">min</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e57373;\">-2500.50 kN·m</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">  |  M</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">max</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#81c784;\">+800.00 kN·m</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'sans-serif\'; font-size:13pt; font-weight:700; color:#ffffff;\">Convenção:</span><span style=\" font-family:\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:8px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'sans-serif\'; font-size:11pt; font-weight:700; color:#81c784;\">(+) Positivo:</span><span style=\" font-family:\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> Tração embaixo → </span><span style=\" font-family:\'sans-serif\'; font-size:11pt; font-weight:700; color:#e0e0e0;\">Armadura Inferior</span><span style=\" font-family:\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> <br /></span><span style=\" font-family:\'sans-serif\'; font-size:11pt; font-weight:700; color:#e57373;\">(-) Negativo:</span><span style=\" font-family:\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> Tração em cima → </span><span style=\" font-family:\'sans-serif\'; font-size:11pt; font-weight:700; color:#e0e0e0;\">Armadura Superior</span><span style=\" font-family:\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; color:#e0e0e0;\"><br /></span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:14px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:14pt; font-weight:700; color:#90caf9; background-color:#252525;\">Reações </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; font-weight:700; color:#e0e0e0;\">Máximo em Apoio A (0.00 m):</span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> </span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; color:#e0e0e0;\"><br /></span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">R</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">min</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e57373;\">-150.00 kN</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">  |  R</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">max</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#81c784;\">+320.50 kN</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#252525;\"><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; font-weight:700; color:#e0e0e0;\">Mínimo em Apoio B (60.00 m):</span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:11pt; color:#e0e0e0;\"> </span><span style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; color:#e0e0e0;\"><br /></span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">R</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">min</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e57373;\">-200.00 kN</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\">  |  R</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0; vertical-align:sub;\">max</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> = </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#81c784;\">+50.00 kN</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:12.5pt; font-weight:700; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'sans-serif\'; font-size:11.5pt; font-weight:700; color:#ffffff;\">Convenção:</span><span style=\" font-family:\'sans-serif\'; font-size:10pt; color:#e0e0e0;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:6px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'sans-serif\'; font-size:10pt; font-weight:700; color:#81c784;\">(+) Para cima:</span><span style=\" font-family:\'sans-serif\'; font-size:10pt; color:#e0e0e0;\"> Reação vertical ascendente. <br /></span><span style=\" font-family:\'sans-serif\'; font-size:10pt; font-weight:700; color:#e57373;\">(-) Para baixo:</span><span style=\" font-family:\'sans-serif\'; font-size:10pt; color:#e0e0e0;\"> Reação vertical descendente. </span></p></body></html>"))
        self.groupBox_5.setTitle(_translate("janela_esforcos_calculo", "Visualizar Detalhes"))
        self.botao_cortante.setText(_translate("janela_esforcos_calculo", "Cortante"))
        self.botao_momento.setText(_translate("janela_esforcos_calculo", "Momento Fletor"))
        self.botao_reacoes.setText(_translate("janela_esforcos_calculo", "Reação de Apoio"))
        self.groupBox_coef.setTitle(_translate("janela_esforcos_calculo", "Estados Limite de Cálculo"))
        self.label.setText(_translate("janela_esforcos_calculo", "<!DOCTYPE html>\n"
"<html lang=\"pt-br\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=yes\">\n"
"    <title>Combinações de Esforços - NBR 6118:2023</title>\n"
"    <style>\n"
"        /* Pequeno reset para garantir consistência entre navegadores */\n"
"        * {\n"
"            margin: 0;\n"
"            padding: 0;\n"
"            box-sizing: border-box;\n"
"        }\n"
"        body {\n"
"            background-color: #2b2b2b;\n"
"            color: #ffffff;\n"
"            font-family: \'Segoe UI\', Roboto, \'Helvetica Neue\', sans-serif;\n"
"            margin: 0;\n"
"            padding: 24px 20px;\n"
"            line-height: 1.4;\n"
"        }\n"
"        /* Estilos globais para melhor legibilidade dos símbolos matemáticos */\n"
"        .math-equation {\n"
"            font-family: \'Times New Roman\', \'Georgia\', serif;\n"
"            font-size: 18pt;\n"
"            padding: 28px 20px;\n"
"            text-align: center;\n"
"            background-color: rgba(255, 255, 255, 0.04);\n"
"            border-radius: 12px;\n"
"            border: 1px solid #4a4a4a;\n"
"            transition: all 0.2s;\n"
"            word-break: break-word;\n"
"            letter-spacing: 0.3px;\n"
"        }\n"
"        /* Bloco de título com destaque lateral */\n"
"        .section-title {\n"
"            color: #f1c40f;\n"
"            font-weight: 700;\n"
"            font-size: 0.95rem;\n"
"            letter-spacing: 0.3px;\n"
"            margin-bottom: 16px;\n"
"            border-left: 4px solid #f1c40f;\n"
"            padding-left: 14px;\n"
"            text-transform: none;\n"
"        }\n"
"        /* Cada bloco principal (ELU / ELS) com espaçamento bem definido */\n"
"        .block-equation {\n"
"            margin-bottom: 52px;   /* Espaço generoso entre os blocos de equação */\n"
"        }\n"
"        /* Último bloco de equação não precisa de margem extra inferior se houver legenda,\n"
"           mas mantemos consistência; a legenda terá seu próprio espaçamento superior */\n"
"        .block-equation:last-of-type {\n"
"            margin-bottom: 48px;\n"
"        }\n"
"        /* Container da legenda - totalmente diferente do fundo das equações */\n"
"        .legend-container {\n"
"            background-color: #212121;  /* tom escuro sólido, diferente do fundo translúcido das equações */\n"
"            border: 1px solid #5f5f5f;\n"
"            border-radius: 14px;\n"
"            padding: 24px 28px;\n"
"            margin-top: 16px;\n"
"            margin-bottom: 28px;\n"
"            box-shadow: 0 2px 6px rgba(0,0,0,0.3);\n"
"            transition: background 0.2s;\n"
"        }\n"
"        /* Estilo do título da legenda, alinhado visualmente com os títulos das equações */\n"
"        .legend-heading {\n"
"            color: #f1c40f;\n"
"            font-weight: 700;\n"
"            font-size: 0.95rem;\n"
"            margin-bottom: 20px;\n"
"            border-left: 4px solid #f1c40f;\n"
"            padding-left: 14px;\n"
"            letter-spacing: 0.2px;\n"
"        }\n"
"        /* Cada linha de definição na legenda */\n"
"        .legend-item {\n"
"            margin-bottom: 12px;\n"
"            line-height: 1.55;\n"
"            font-size: 0.9rem;\n"
"            color: #e0e0e0;\n"
"        }\n"
"        .legend-item b {\n"
"            color: #f5f5f5;\n"
"            font-weight: 600;\n"
"        }\n"
"        .legend-item sub, .legend-item sup {\n"
"            font-size: 0.75rem;\n"
"        }\n"
"        /* pequeno ajuste para ícones matemáticos dentro da legenda */\n"
"        .legend-item i {\n"
"            font-style: italic;\n"
"        }\n"
"        /* rodapé de referência */\n"
"        .ref-footer {\n"
"            font-family: \'Segoe UI\', sans-serif;\n"
"            font-size: 0.75rem;\n"
"            color: #f1c40f;\n"
"            text-align: right;\n"
"            border-top: 1px dashed #5a5a5a;\n"
"            padding-top: 14px;\n"
"            margin-top: 12px;\n"
"            opacity: 0.85;\n"
"        }\n"
"        /* responsividade: reduzir padding em telas pequenas */\n"
"        @media (max-width: 600px) {\n"
"            body {\n"
"                padding: 16px 12px;\n"
"            }\n"
"            .math-equation {\n"
"                font-size: 15pt;\n"
"                padding: 20px 12px;\n"
"            }\n"
"            .legend-container {\n"
"                padding: 18px 20px;\n"
"            }\n"
"            .block-equation {\n"
"                margin-bottom: 40px;\n"
"            }\n"
"        }\n"
"        /* pequena correção para garantir quebra de linha em equações longas */\n"
"        .math-equation br {\n"
"            display: none;\n"
"        }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"\n"
"    <!-- BLOCO 1: ELU - Estado Limite Último -->\n"
"    <div class=\"block-equation\">\n"
"        <div class=\"section-title\">\n"
"            ELU — Estado Limite Último: Combinação Normal\n"
"        </div>\n"
"        <div class=\"math-equation\">\n"
"            <i>F</i><sub>d</sub> = &gamma;<sub>g</sub><i>F</i><sub>gk</sub> + \n"
"            &gamma;<sub>q</sub> (<i>F</i><sub>q1k</sub> + &Sigma;&psi;<sub>0j</sub><i>F</i><sub>qjk</sub>) + \n"
"            &gamma;<sub>&epsilon;q</sub>&psi;<sub>0&epsilon;</sub><i>F</i><sub>&epsilon;qk</sub>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <!-- BLOCO 2: ELS - Estado Limite de Serviço (Combinação Frequente) -->\n"
"    <div class=\"block-equation\">\n"
"        <div class=\"section-title\">\n"
"            ELS — Estado Limite de Serviço: Combinação Frequente\n"
"        </div>\n"
"        <div class=\"math-equation\">\n"
"            <i>F</i><sub>d,ser</sub> = &Sigma;<i>F</i><sub>gi,k</sub> + \n"
"            &psi;<sub>1</sub><i>F</i><sub>q1k</sub> + &Sigma;&psi;<sub>2j</sub><i>F</i><sub>qj,k</sub>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <!-- LEGENDA: agora com fundo completamente distinto das equações, melhor hierarquia visual -->\n"
"    <div class=\"legend-container\">\n"
"        <div class=\"legend-heading\">\n"
"            Legenda dos Componentes\n"
"        </div>\n"
"        \n"
"        <div class=\"legend-item\">\n"
"            <b><i>F</i><sub>gk</sub> / <i>F</i><sub>gi,k</sub>:</b> Esforços/Ações Permanentes (Peso Próprio, Pavimentação e Guarda-rodas)\n"
"        </div>\n"
"        <div class=\"legend-item\">\n"
"            <b><i>F</i><sub>q1k</sub>:</b> Ação Variável Principal (Carga Móvel / Trem‑tipo)\n"
"        </div>\n"
"        <div class=\"legend-item\">\n"
"            <b><i>F</i><sub>qjk</sub> / <i>F</i><sub>&epsilon;qk</sub>:</b> Ações Variáveis Secundárias e Efeitos de Recalque ou Temperatura\n"
"        </div>\n"
"        <div class=\"legend-item\">\n"
"            <b>&gamma;<sub>g</sub>, &gamma;<sub>q</sub>, &gamma;<sub>&epsilon;q</sub>:</b> Coeficientes de ponderação das ações (Majoradores)\n"
"        </div>\n"
"        <div class=\"legend-item\">\n"
"            <b>&psi;<sub>0</sub>, &psi;<sub>1</sub>, &psi;<sub>2</sub>:</b> Fatores de redução para combinações (Simultaneidade e Frequência)\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <!-- Referência normativa -->\n"
"    <div class=\"ref-footer\">\n"
"        Referência: NBR 6118:2023\n"
"    </div>\n"
"\n"
"</body>\n"
"</html>"))
        self.box_coef.setTitle(_translate("janela_esforcos_calculo", "Coeficientes de Cálculo"))
        self.radio_automatico.setText(_translate("janela_esforcos_calculo", "Normativo"))
        self.radio_personalizado.setText(_translate("janela_esforcos_calculo", "Personalizado"))
        self.html_normativo.setText(_translate("janela_esforcos_calculo", "    <html>\n"
"    <body style=\'background-color: #2b2b2b; color: #ffffff; font-family: \"Segoe UI\", sans-serif; padding: 15px;\'>\n"
"        <table style=\'width: 100%; border-collapse: collapse; font-size: 10pt; table-layout: fixed;\'>\n"
"            <tr>\n"
"                <td colspan=\"2\" style=\'padding: 5px 0 10px 0;\'>\n"
"                    <b style=\'color: #f1c40f; font-size: 11pt;\'>COEFICIENTES DE PONDERAÇÃO</b>\n"
"                </td>\n"
"            </tr>\n"
"            <tr style=\'border-bottom: 1px solid #444;\'>\n"
"                <td style=\'padding: 8px 0; vertical-align: middle; width: 65%;\'>Ações permanentes (&gamma;<sub>g</sub>):</td>\n"
"                <td style=\'text-align: right; font-weight: bold; vertical-align: middle; width: 35%;\'>1,35 <span style=\'font-size: 8pt; color: #aaa; font-weight: normal;\'>(desf.)</span> / 1,0</td>\n"
"            </tr>\n"
"            <tr style=\'border-bottom: 1px solid #444;\'>\n"
"                <td style=\'padding: 8px 0; vertical-align: middle;\'>Ações variáveis (&gamma;<sub>q</sub>):</td>\n"
"                <td style=\'text-align: right; font-weight: bold; vertical-align: middle;\'>1,50</td>\n"
"            </tr>\n"
"            <tr style=\'border-bottom: 1px solid #444;\'>\n"
"                <td style=\'padding: 8px 0; vertical-align: middle;\'>Variações de temperatura (&gamma;<sub>&epsilon;q</sub>):</td>\n"
"                <td style=\'text-align: right; font-weight: bold; vertical-align: middle;\'>1,20</td>\n"
"            </tr>\n"
"            <tr><td colspan=\"2\" style=\'padding: 10px 0;\'></td></tr>\n"
"            <tr>\n"
"                <td colspan=\"2\" style=\'padding: 5px 0 10px 0;\'>\n"
"                    <b style=\'color: #f1c40f; font-size: 11pt;\'>FATORES DE COMBINAÇÃO E REDUÇÃO</b>\n"
"                </td>\n"
"            </tr>\n"
"            <tr style=\'border-bottom: 1px solid #444;\'>\n"
"                <td style=\'padding: 8px 0; vertical-align: middle;\'>Fator de combinação (&psi;<sub>0</sub>):</td>\n"
"                <td style=\'text-align: right; font-weight: bold; vertical-align: middle;\'>0,60</td>\n"
"            </tr>\n"
"            <tr style=\'border-bottom: 1px solid #444;\'>\n"
"                <td style=\'padding: 8px 0; vertical-align: middle;\'>Redução Ação Móvel (&psi;<sub>1</sub>):</td>\n"
"                <td style=\'text-align: right; font-weight: bold; vertical-align: middle;\'>0,50</td>\n"
"            </tr>\n"
"            <tr style=\'border-bottom: 1px solid #444;\'>\n"
"                <td style=\'padding: 8px 0; vertical-align: middle;\'>Redução Temperatura (&psi;<sub>2</sub>):</td>\n"
"                <td style=\'text-align: right; font-weight: bold; vertical-align: middle;\'>0,30</td>\n"
"            </tr>\n"
"        </table>\n"
"        <div style=\'font-family: \"Segoe UI\", sans-serif; font-size: 8.5pt; color: #f1c40f; padding-top: 10px; text-align: right; border-top: 1px dashed #444; margin-top: 20px;\'>\n"
"            Referência: NBR 8681:2003\n"
"        </div>\n"
"    </body>\n"
"    </html>"))
        self.html_personalizado.setText(_translate("janela_esforcos_calculo", "<html>\n"
"    <body style=\'background-color: #2b2b2b; color: #777777; font-family: \"Segoe UI\", sans-serif; padding: 15px;\'>\n"
"        <table style=\'width: 100%; border-collapse: collapse; font-size: 10pt; table-layout: fixed;\'>\n"
"            <tr>\n"
"                <td colspan=\"2\" style=\'padding: 5px 0 10px 0;\'>\n"
"                    <b style=\'color: #555555; font-size: 11pt;\'>COEFICIENTES DE PONDERAÇÃO</b>\n"
"                </td>\n"
"            </tr>\n"
"            <tr style=\'border-bottom: 1px solid #333333;\'>\n"
"                <td style=\'padding: 8px 0; vertical-align: middle; width: 65%;\'>Ações permanentes (&gamma;<sub>g</sub>):</td>\n"
"                <td style=\'text-align: right; font-weight: bold; vertical-align: middle; width: 35%;\'>---</td>\n"
"            </tr>\n"
"            <tr style=\'border-bottom: 1px solid #333333;\'>\n"
"                <td style=\'padding: 8px 0; vertical-align: middle;\'>Ações variáveis (&gamma;<sub>q</sub>):</td>\n"
"                <td style=\'text-align: right; font-weight: bold; vertical-align: middle;\'>---</td>\n"
"            </tr>\n"
"            <tr style=\'border-bottom: 1px solid #333333;\'>\n"
"                <td style=\'padding: 8px 0; vertical-align: middle;\'>Variações de temperatura (&gamma;<sub>&epsilon;q</sub>):</td>\n"
"                <td style=\'text-align: right; font-weight: bold; vertical-align: middle;\'>---</td>\n"
"            </tr>\n"
"            <tr><td colspan=\"2\" style=\'padding: 10px 0;\'></td></tr>\n"
"            <tr>\n"
"                <td colspan=\"2\" style=\'padding: 5px 0 10px 0;\'>\n"
"                    <b style=\'color: #555555; font-size: 11pt;\'>FATORES DE COMBINAÇÃO E REDUÇÃO</b>\n"
"                </td>\n"
"            </tr>\n"
"            <tr style=\'border-bottom: 1px solid #333333;\'>\n"
"                <td style=\'padding: 8px 0; vertical-align: middle;\'>Fator de combinação (&psi;<sub>0</sub>):</td>\n"
"                <td style=\'text-align: right; font-weight: bold; vertical-align: middle;\'>---</td>\n"
"            </tr>\n"
"            <tr style=\'border-bottom: 1px solid #333333;\'>\n"
"                <td style=\'padding: 8px 0; vertical-align: middle;\'>Redução Ação Móvel (&psi;<sub>1</sub>):</td>\n"
"                <td style=\'text-align: right; font-weight: bold; vertical-align: middle;\'>---</td>\n"
"            </tr>\n"
"            <tr style=\'border-bottom: 1px solid #333333;\'>\n"
"                <td style=\'padding: 8px 0; vertical-align: middle;\'>Redução Temperatura (&psi;<sub>2</sub>):</td>\n"
"                <td style=\'text-align: right; font-weight: bold; vertical-align: middle;\'>---</td>\n"
"            </tr>\n"
"        </table>\n"
"    </body>\n"
"    </html>"))
        self.groupBox.setTitle(_translate("janela_esforcos_calculo", "Visualizar Resultados"))
        self.radio_elu.setText(_translate("janela_esforcos_calculo", "Estado Limite Último (ELU)"))
        self.radio_els.setText(_translate("janela_esforcos_calculo", "Estado Limite de Serviço (ELS)"))
